# Generated by Django 5.1.7 on 2025-03-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_profile_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=True, help_text='Commission amount per sale', max_digits=10),
        ),
    ]
