# Generated by Django 5.1.7 on 2025-03-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_alter_review_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Wholesale Opportunity', 'verbose_name_plural': 'Wholesale Opportunities'},
        ),
        migrations.AddField(
            model_name='deal',
            name='certifications',
            field=models.TextField(blank=True, help_text='Certifications, compliance standards, or quality assurances', null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='lead_time',
            field=models.CharField(blank=True, help_text='Estimated time from order to delivery', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='min_order',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum order quantity', null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='origin',
            field=models.CharField(blank=True, help_text='Country or region of manufacture', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='ship_africa',
            field=models.BooleanField(default=False, help_text='Available for shipping to Africa'),
        ),
        migrations.AddField(
            model_name='deal',
            name='ship_asia',
            field=models.BooleanField(default=False, help_text='Available for shipping to Asia'),
        ),
        migrations.AddField(
            model_name='deal',
            name='ship_australia',
            field=models.BooleanField(default=False, help_text='Available for shipping to Australia/Oceania'),
        ),
        migrations.AddField(
            model_name='deal',
            name='ship_domestic',
            field=models.BooleanField(default=False, help_text='Available for domestic shipping'),
        ),
        migrations.AddField(
            model_name='deal',
            name='ship_europe',
            field=models.BooleanField(default=False, help_text='Available for shipping to Europe'),
        ),
        migrations.AddField(
            model_name='deal',
            name='ship_international',
            field=models.BooleanField(default=False, help_text='Available for international shipping'),
        ),
        migrations.AddField(
            model_name='deal',
            name='ship_north_america',
            field=models.BooleanField(default=False, help_text='Available for shipping to North America'),
        ),
        migrations.AddField(
            model_name='deal',
            name='ship_south_america',
            field=models.BooleanField(default=False, help_text='Available for shipping to South America'),
        ),
        migrations.AddField(
            model_name='deal',
            name='shipping_terms',
            field=models.CharField(blank=True, help_text='Standard international shipping terms', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
