# Generated by Django 5.1.7 on 2025-03-19 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_adminchatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminChatMessage',
        ),
    ]
