# Generated by Django 5.1.7 on 2025-03-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0012_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount amount (e.g., 10 for $10 off)', max_digits=10),
        ),
    ]
