# Generated by Django 5.1.7 on 2025-03-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0014_likedproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_address',
            new_name='street_address',
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='Default City', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='Cash on Delivery', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='province',
            field=models.CharField(default='Province Name', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
