# Generated by Django 5.1.7 on 2025-03-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0015_rename_ordered_at_order_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='co_admin_photos/')),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nationality_card_front', models.ImageField(blank=True, null=True, upload_to='nationality_cards/')),
                ('nationality_card_back', models.ImageField(blank=True, null=True, upload_to='nationality_cards/')),
                ('dob_certificate', models.ImageField(blank=True, null=True, upload_to='dob_certificates/')),
                ('date_of_birth', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
