# Generated by Django 5.1.7 on 2025-03-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0017_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_request_manager_btn',
            field=models.BooleanField(default=False),
        ),
    ]
