# Generated by Django 5.1.7 on 2025-03-24 05:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0018_profile_show_request_manager_btn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSetting',
        ),
        migrations.AlterModelOptions(
            name='coadmin',
            options={'ordering': ['-created_at'], 'verbose_name': 'Co-Administrator', 'verbose_name_plural': 'Co-Administrators'},
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='coadmin',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='co_admin_photos/'),
        ),
    ]
