# Generated by Django 5.1.7 on 2025-03-24 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0020_coadmin_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoAdmin',
        ),
    ]
