# Generated by Django 5.1.7 on 2025-03-24 17:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0021_delete_coadmin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='co_admin_photos/')),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?\\d{10,15}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nationality_card_front', models.ImageField(blank=True, null=True, upload_to='nationality_cards/')),
                ('nationality_card_back', models.ImageField(blank=True, null=True, upload_to='nationality_cards/')),
                ('dob_certificate', models.ImageField(blank=True, null=True, upload_to='dob_certificates/')),
                ('date_of_birth', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coadmin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Co-Administrator',
                'verbose_name_plural': 'Co-Administrators',
                'ordering': ['-created_at'],
            },
        ),
    ]
