# Generated by Django 5.1.7 on 2025-03-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0023_cart_updated_at_cartorder_cartorderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderitem',
            name='cart_order',
        ),
        migrations.RemoveField(
            model_name='cartorderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='order_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='CartOrder',
        ),
        migrations.DeleteModel(
            name='CartOrderItem',
        ),
    ]
