# Generated by Django 5.1.7 on 2025-03-27 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0025_userseller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSeller',
        ),
    ]
