# Generated by Django 5.1.7 on 2025-05-02 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0031_conversation_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
