# Generated by Django 5.1.7 on 2025-05-11 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0036_alter_notification_notification_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='withdrawal_proofs/')),
                ('notes', models.TextField(blank=True, help_text="Seller's notes regarding the withdrawal", null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes regarding the withdrawal', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet Withdrawal',
                'verbose_name_plural': 'Wallet Withdrawals',
                'ordering': ['-created_at'],
            },
        ),
    ]
