# Generated by Django 5.1.7 on 2025-06-10 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0038_productshare'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductShare',
        ),
    ]
