# Generated by Django 4.2.7 on 2025-06-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0040_sharerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralcommission',
            name='is_given',
            field=models.BooleanField(default=False),
        ),
    ]
